### ISSUE TITLE
gwteventservice does not compile with java 1.5

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google-code-export/gwteventservice#14]
```
What steps will reproduce the problem?
1. ant dist

What is the expected output? What do you see instead?
expect compilation

instead, I get this error:

compile:
    [javac] Compiling 27 source files to 
/Users/ranger/cvs/gwteventservice/build/production
    [javac] Compiling 35 source files to 
/Users/ranger/cvs/gwteventservice/build/production
    [javac] 
/Users/ranger/cvs/gwteventservice/module/EventService/src/de/novanic/
eventservice/service/registry/user/DomainUserMapping.java:29: cannot 
find symbol
    [javac] symbol  : class ConcurrentSkipListSet
    [javac] location: package java.util.concurrent
    [javac] import java.util.concurrent.ConcurrentSkipListSet;
    [javac]                             ^
    [javac] 
/Users/ranger/cvs/gwteventservice/module/EventService/src/de/novanic/
eventservice/config/loader/WebDescriptorConfigurationLoader.java:76: 
cannot find symbol
    [javac] symbol  : method isEmpty()
    [javac] location: class java.lang.String
    [javac]         return aParameterValue != null && 
!aParameterValue.trim().isEmpty() && 
StringUtil.isNumeric(aParameterValue);
    [javac]                                                                ^
    [javac] 
/Users/ranger/cvs/gwteventservice/module/EventService/src/de/novanic/
eventservice/service/registry/user/DomainUserMapping.java:56: cannot 
find symbol
    [javac] symbol  : class ConcurrentSkipListSet
    [javac] location: class 
de.novanic.eventservice.service.registry.user.DomainUserMapping
    [javac]         myDomainUserInfoMap.putIfAbsent(aDomain, new 
ConcurrentSkipListSet<UserInfo>());
    [javac]                                                      ^
    [javac] 
/Users/ranger/cvs/gwteventservice/module/EventService/src/de/novanic/
eventservice/service/registry/user/DomainUserMapping.java:102: cannot 
find symbol
    [javac] symbol  : class ConcurrentSkipListSet
    [javac] location: class 
de.novanic.eventservice.service.registry.user.DomainUserMapping
    [javac]                 myDomainUserInfoMap.remove(aDomain, new 
ConcurrentSkipListSet<UserInfo>());
    [javac]                                                         ^
    [javac] 4 errors

BUILD FAILED


What version of the product are you using? On what operating system?
svn 1.1 branch

Please provide any additional information below.

String.isEmpty() and ConcurrentSkipListSet are new in Java 6.  Attached is a 
patch that fixes the build to work with java 1.5.
```

Original issue reported on code.google.com by `rangerr...@gmail.com` on 19 Mar 2010 at 11:46

Attachments:
- [gwteventservice-java15.patch](https://storage.googleapis.com/google-code-attachments/gwteventservice/issue-14/comment-0/gwteventservice-java15.patch)
